# Generated by Django 4.1.5 on 2023-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_students', to='courses_platform.course'),
        ),
    ]
