# Generated by Django 4.1.5 on 2023-04-19 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_platform', '0003_alter_user_enrolled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='passers',
            field=models.ManyToManyField(blank=True, related_name='courses_passed', to=settings.AUTH_USER_MODEL),
        ),
    ]
