# Generated by Django 4.1.5 on 2023-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_platform', '0005_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/'),
        ),
    ]
